# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 200
    level: warning

  # Allow multiple documents in a file (for Kubernetes manifests, etc.)
  document-start: disable

  # Indentation settings
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values - allow yes/no in addition to true/false
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Braces and brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Trailing spaces
  trailing-spaces: enable

# Ignore patterns
ignore: |
  .git/
  vendor/
  docs/specifications/api/
